### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by tenebris0011** [TaylanTatli/StartPage#1]
I pulled your project the other day, when you are reddit.
It was something I quite enjoyed.
Something I might recommend is to add 
`"targert="_blank"`
to the end of all your hyper links (like below).
`<a href="https://facebook.com" target="_blank">`
The reason I recommend this, is because it opens the link in a new tab.

**Comment by TaylanTatli** [comment]
Thank you. My new tab page is this start page. So I don't like links to open in a new tab. All i have to do is ctrl+t and then click the link. It's kind of personal choice.

**Comment by TaylanTatli** [comment]
Btw, your reference link is wrong. I don't know who is wysuszony. :smiley:     
My reddit link is https://www.reddit.com/user/taylantatli/

**Comment by tenebris0011** [comment]
I understand that its prefence , just thought I might recommend it. I will
also fix my reference link so that you get the credit you deserve.

On Sun, Feb 28, 2016, 9:41 PM Taylan Tatlı <notifications@github.com> wrote:

> Thank you. My new tab page is this start page. So I don't like links to
> open in a new tab. All i have to do is ctrl+t and then click the link. It's
> kind of personal choice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TaylanTatli/StartPage/issues/1#issuecomment-190026309>
> .
>
-- 

Nathanial Wilson
M: (405)-664-9527
E: wilson.nathanial95@gmail.com

**Comment by TaylanTatli** [comment]
Thank you.
